### ISSUE TITLE
Crashes without CoreFoundation.framework in iOS8

### ISSUE THREAD

**Issue by rreusser** [wmcmahan/react-native-calendar-events#5]
After installing this module, the app compiles fine but crashes instantly using the iOS 8.2 simulator (anything less than iOS9, I believe, and before loading RN) unless `CoreFoundation.framework` is linked with `Optional` status. Due to an unhelpful error message, it took a lengthy git bisect to track down sometime after the fact, so it seems—unless this is symptomatic of some other issue—that `CoreFoundation.framework` (Status: Optional) could perhaps be included in the installation instructions. Unless, of course, there's a more effective/correct solution.

Error message:

```
dyld: Symbol not found: ___NSArray0__
  Referenced from: /Users/rreusser/Library/Developer/CoreSimulator/Devices/.../data/Containers/Bundle/Application/.../MyApp.app/MyApp
  Expected in: /Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 8.2.simruntime/Contents/Resources/RuntimeRoot/System/Library/Frameworks/CoreFoundation.framework/CoreFoundation
 in /Users/rreusser/Library/Developer/CoreSimulator/Devices/.../data/Containers/Bundle/Application/.../MyApp.app/MyApp
```

**Comment by wmcmahan** [comment]
Thanks @rreusser, great point. I will make note in the instructions.

**Comment by rreusser** [comment]
Want me to make a quick PR? I'm probably part of the react-native inspired influx of JS developers into the Xcode world, so wanted to make sure there wasn't a more appropriate solution. But if it makes sense, I'm glad to make a quick PR.

**Comment by wmcmahan** [comment]
Absolutely, I'm part of the JS influx also and PR's are always welcome :) Any documentation around possible errors is always helpful.

**Comment by nicinabox** [comment]
Just ran into this issue. @rreusser @wmcmahan any progress on that PR?

**Comment by rreusser** [comment]
@nicinabox Yup! Sorry I failed to submit previously. Submitted a quick PR with the note.

**Comment by jasan-s** [comment]
The simulator crashes still without core Foundation framework in ios 10.3.
